name: Build on fedora

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/bailuk/java-gtk/gtk4-fedora:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate source code
        run: make gen

      - name: Build library
        run: make

      - name: Build exsamples
        run: make examples

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: java-gtk
          path: java-gtk/build/libs/*
          if-no-files-found: error
