name: Build inside container

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/bailuk/java-gtk/gtk4:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate source code
        run: ./gradlew generator:generate

      - name: Generate JNI headers
        run: ./gradlew java-gtk:classes

      - name: Compile C code
        run: make -C glue -j 3

      - name: Build library
        run: ./gradlew java-gtk:build

      - name: Build exsamples
        run: ./gradlew examples:build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: java-gtk
          path: java-gtk/build/libs/*
          if-no-files-found: error
