name: Build on debian

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/bailuk/java-gtk/gtk4-debian:latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Accept permission
        run: git config --global --add safe.directory /__w/java-gtk/java-gtk

      - name: Display tags
        run: git tag

      - name: Display version
        run: ./gradlew cV

      - name: Generate source code
        run: make gen

      - name: Build library
        run: make

      - name: Build exsamples
        run: make examples

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: java-gtk
          path: java-gtk/build/libs/*
          if-no-files-found: error
